name: Push to main

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  pages: write

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Pandoc specification builder
        uses: legreq/pandoc-spec@main
        with:
          include-repository: true
          node-version: ${{ vars.NODE_VERSION }}
          include-pages: true
